name: Deploy admin front end
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: yarn install --frozen-lockfile

      - run: npx nx workspace-lint
      - run: npx nx affected --target=lint --parallel=3
      #- run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.3
        with:
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: gsutil -m rsync -d -c -r dist/apps/mmmp gs://mmmp-admin-frontend

